### ISSUE TITLE
 UnitRegistry.parse_units(None) does not work anymore in pint 0.21

### ISSUE THREAD

**Issue by reszelaz** [hgrecco/pint#1768]
With python 3.11 and pint 0.21:

```
In [1]: import pint

In [2]: UR = pint.UnitRegistry()

In [3]: UR.parse_units(None)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 UR.parse_units(None)

File ~/miniconda3/envs/taurus-py3.11/lib/python3.11/site-packages/pint/facets/plain/registry.py:1078, in PlainRegistry.parse_units(self, input_string, as_delta, case_sensitive)
   1057 """Parse a units expression and returns a UnitContainer with
   1058 the canonical names.
   1059 
   (...)
   1075 
   1076 """
   1077 for p in self.preprocessors:
-> 1078     input_string = p(input_string)
   1079 units = self._parse_units(input_string, as_delta, case_sensitive)
   1080 return self.Unit(units)

File ~/miniconda3/envs/taurus-py3.11/lib/python3.11/site-packages/pint/facets/plain/registry.py:233, in PlainRegistry.__init__.<locals>.<lambda>(string)
    231 self.preprocessors = preprocessors or []
    232 # use a default preprocessor to support "%"
--> 233 self.preprocessors.insert(0, lambda string: string.replace("%", " percent "))
    235 #: mode used to fill in the format defaults
    236 self.separate_format_defaults = separate_format_defaults

AttributeError: 'NoneType' object has no attribute 'replace'
```

With pint 0.20.1:

```
In [1]: import pint

In [2]: UR = pint.UnitRegistry()

In [3]: UR.parse_units(None)
Out[3]: <Unit('dimensionless')>
```

The error happens on line introduced in https://github.com/hgrecco/pint/pull/1661/commits/00f1f55468da760e0e5b9eda9d8a4d5a8b764572 as part of https://github.com/hgrecco/pint/pull/1661

**Comment by jules-ch** [comment]
According to the docstring, pars_units should only use `str` as inputs.
This usage has never been supported.

**Comment by jules-ch** [comment]
https://github.com/hgrecco/pint/blob/5643c32f7f2c886015df459f26b4d72adaee1207/pint/facets/plain/registry.py#L1031-L1056

**Comment by reszelaz** [comment]
Thanks @jules-ch for your fast answer! Then we should use `UR.parse_units("")` instead to achieve the same behavior?

**Comment by jules-ch** [comment]
Yes if you want to still use this function. :)
