### ISSUE TITLE
Regression: Units from derived unit registry no longer instance of pint.Unit

### ISSUE THREAD

**Issue by mikapfl** [hgrecco/pint#1631]
Hi,

when using Pint 0.20, a unit from a subclass of pint.UnitRegistry is no longer considered an instance of pint.Unit. Hard to explain, this code shows it:

```python
import pint

class MyUnitRegistry(pint.UnitRegistry):
    pass

print(isinstance(MyUnitRegistry().Unit("m"), pint.Unit))
```
With Pint 0.19.2, this prints `True`, with Pint 0.20, it prints `False`.

This leads to weird behaviour in e.g. pint_xarray when trying to check if something is a unit (done with `isinstance(pint.Unit)`) when the unit is derived from a subclass derived from pint.UnitRegistry. In my specific use case, I'm combining [pint_xarray](https://pint-xarray.readthedocs.io/en/stable/) and [openscm-units](https://openscm-units.readthedocs.io/en/latest/), and the combination breaks if Pint 0.20 is used.

I'm not quite sure if this can be solved / worked around downstream. Wanting to check if something is a unit via `isinstance` sounds reasonable, and subclassing also doesn't sound super wrong.

**Comment by jules-ch** [comment]
It seems to originate from subclassing UnitRegistry:

```python
from pint import UnitRegistry
from pint import Unit

ureg = UnitRegistry()
print(isinstance(ureg.Unit("m"), Unit))
```

prints True

**Comment by jules-ch** [comment]
As stated by the pint module:

```python
# Default Quantity, Unit and Measurement are the ones
# build in the default registry.
```

**Comment by jules-ch** [comment]
you should use this instead : 

```python

import pint

class MyUnitRegistry(pint.UnitRegistry):
    pass
ureg = MyUnitRegistry()

print(isinstance(ureg.Unit("m"), ureg.Unit))
```

**Comment by jules-ch** [comment]
What do you think @hgrecco ?

**Comment by hgrecco** [comment]
Indeed, `Unit`, `Quantity` and `Measurement` classes in `pint.` are the ones in the default registry. So the solution proposed by @jules-ch . This is also safer as these are SharedRegistry objects and therefore there are tight to a specific registry instance. However, I do understand that this might break things but I would like to understand exactly how to be sure that the solution proposes by @jules-ch is not enough.

**Comment by hgrecco** [comment]
Maybe there is another way. 

First idea
Do not create a `Unit`, `Quantity` and `Measurement` class if the Registry class does not implement a specific `_quantity_class`,  `_unit_class` or `_measurement_class` and use the class. 
This will fix trivial registry subclassing (i.e. subclassing that do not attempt to change _quantity_class, _unit_class or _measurement_class)

Second idea:
Do not create a `Unit`, `Quantity` and `Measurement` de novo but rather subclassing respective classes in parent objects.

This will fix all registry subclassing (i.e. subclassing that do not attempt to change _quantity_class, _unit_class or _measurement_class)

**Comment by mikapfl** [comment]
Hi,

earlier, I did

```python
import pint

class MyUnitRegistry(pint.UnitRegistry):
    pass
ureg = MyUnitRegistry()

print(isinstance(ureg.Unit("m"), pint.unit.Unit))
```

Which works in pre-0.20 pint, but breaks on 0.20 because `pint.unit.Unit` does not exist any more. I think that is fine, `pint.unit.Unit` doesn't look like public API to me, so I always kinda expected it to break, but I haven't found a replacement which can be used to ask "is this any kind of Pint unit, from any registry?".

Probably it would be possible to switch to using `ureg.Unit`, if in any context where we want to check if something is a unit, the respective unit registry is known, maybe @keewis knows if that is the case in pint_xarray?

Cheers,

Mika

**Comment by hgrecco** [comment]
I have just created something that works in between idea 1 and 2, and make the current test pass
```python
import pint

# Test registry subclassing
class MyRegistry(pint.UnitRegistry):
    pass

assert MyRegistry.Quantity is pint.UnitRegistry.Quantity
assert MyRegistry.Unit is pint.UnitRegistry.Unit

ureg = MyRegistry()

u = ureg.meter
assert isinstance(u, ureg.Unit)
assert isinstance(u, pint.Unit)

q = 2 * ureg.meter
assert isinstance(q, ureg.Quantity)
assert isinstance(q, pint.Quantity)
```

I think this is both correct and simplifies registry subclassing and asserting if `isinstance`

**Comment by mikapfl** [comment]
> I would appreciate if you could pull the develop branch and see if this works for you.

Indeed, current develop works without code changes in downstream libraries (pint_xarray, openscm_units, or primap2). Thanks for the swift reaction!
I also looked through your pull request, but I fear I don't really understand the class-magic that is going on in there, I can just see that it works now. :sweat_smile:

**Comment by hgrecco** [comment]
@mikapfl awesome 

Briefly, the way it works is that the `UnitRegistry` is assembled by inheriting functionality from different Facets. When a certain facet is used as a parent for the registry class (e.g. `NumpyRegistry`) the corresponding facet has to be used as a parent for the quantity class (e.g. `QuantityClass`). Pint does this transparently and consistently by inspecting the registry mro. But it we were creating a new class for each registry class, now we reuse them if possible.

By the way, it would be nice to have a mechanism to signal related projects about a new pint version so we can test everything while in beta.

**Comment by mikapfl** [comment]
> By the way, it would be nice to have a mechanism to signal related projects about a new pint version so we can test everything while in beta.

True, is there a mailing list or other communication channel I could subscribe to be notified of beta-status? Maybe I can also set up some github actions which run with pint master regularly, then we also get some advanced notification.

**Comment by dalito** [comment]
If pint would do github releases you could follow "release"-notifications. I think it does not work with tags alone.

**Comment by hgrecco** [comment]
@mikapfl Indeed, running against master is the good way as nothing is committed to master until test are passing. The only downside is that you will be testing against all dev version of Pint (not rc). And also you test will not be run unless you commit something in your project.

I wonder if there is a way to notify automatically external projects when a new rc version is out there. i.e. before release, we freeze the code and change the version to `0.20.dev0` to `0.20.rc1`.

**Comment by hgrecco** [comment]
@dalito but this works after the fact, right? It would be nice if downstream projects can test against release candidates automatically.

**Comment by keewis** [comment]
I think the best way forward is to have every project have a scheduled CI that regularly (daily, weekly?) runs their testsuite against the development version of `pint` and any other dependencies. The only caveat is that you will then have to give each project time to react to the failing test suite before each release. For example, here's [`xarray`'s CI](https://github.com/pydata/xarray/blob/main/.github/workflows/upstream-dev-ci.yaml).

(And, by the way, I'd recommend `pint` to do the same)

**Comment by dalito** [comment]
Yes, it should send notifications for any release.

**Comment by hgrecco** [comment]
I think we should add this to the docs. Maybe we take the section "Using Pint in your projects" to create a new independent page and add there recommendations for testing.

**Comment by hgrecco** [comment]
Just released 0.20.1 fixing this.
Thanks for reporting
